#!/bin/sh

if [ ! -f /etc/.firstboot ]; then
  echo "First Boot!\n";
  # first we expand the filesystem
  raspi-config --expand-rootfs
  # Do other setup stuff here?



  #generate the firstboot timestamp
  date > /etc/.firstboot
  #force a reboot
  shutdown -r now
fi
