#!/bin/sh
# Script to enable the Raspwn Playground on Apache2 (instead of Nginx)

#First disable Apache2 Playground
rm -vf /etc/apache2/sites-enabled/*
a2ensite wackopicko.raspwn.org
a2ensite default
a2ensite default-ssl
cp /etc/apache2/ports.conf-nginx /etc/apache2/ports.conf

#Now enable Nginx Playground
rm /etc/nginx/sites-enabled/*
ln -s /etc/nginx/sites-available/playground.raspwn.org-wifi /etc/nginx/sites-enabled/playground.raspwn.org-wifi

# Now restart
service apache2 restart
service nginx restart

update-rc.d apache2 defaults
update-rc.d nginx defaults

/bin/echo -e  'RasPwn Web Playground is now configured to use Nginx over Wifi ONLY.';
/bin/echo -e  '';
/bin/echo -e 'Use \e[1mplayground-cfg-apache\e[0m to use Apache2 as the http server';
/bin/echo -e 'Use \e[1mplayground-cfg-apache-promisc\e[0m to also listen on eth0 \e[31m(DANGEROUS!)\e[39m';
/bin/echo -e 'Use \e[1mplayground-cfg-nginx-promisc\e[0m to use Nginx AND also listen on eth0 \e[31m(DANGEROUS!)\e[39m';
/bin/echo -e 'Use \e[1mplayground-cfg-mix\e[0m for BOTH Apache2(192.168.99.13) and Nginx(192.168.99.7)';


